CREATE OR REPLACE FUNCTION addrNull()
RETURNS TRIGGER AS
$$
DECLARE num int;
BEGIN

	SELECT COUNT(*) INTO num
	FROM MUSICIAN
	WHERE addr=NEW.addr;

	IF num=3 THEN
		NEW.addr := NULL;
		RETURN NEW;
	END IF;
	RETURN NEW;
END;
$$
LANGUAGE plpgsql;



CREATE TRIGGER HOUSE_MAX_CAP
BEFORE INSERT OR UPDATE
OF addr
ON MUSICIAN
FOR EACH ROW
EXECUTE PROCEDURE addrNull();